"""
Renders a ROS environment as a plain script to source, so a workspace can be
used without nix develop or wrapped binaries.

The non-ROS packages are propagated rather than merged into the environment,
so their paths are added explicitly. The environment's own ament hooks are
then evaluated once, here, and the resulting variables written out as exports
that prepend to whatever the sourcing shell already has.
"""

import argparse
import json
import os
import shlex
import subprocess
import sys

DUMP_ENV = 'import json, os; print(json.dumps(dict(os.environ)))'

# Variables bash sets on its own, which should not end up in the script.
SHELL_NOISE = {'PWD', 'OLDPWD', 'SHLVL', '_'}


def prepend(env, var, value, sep=':'):
    env[var] = value + (sep + env[var] if env.get(var) else '')


def add_other_packages(env, paths, site_packages):
    for p in paths:
        if os.path.isdir(f'{p}/bin'):
            prepend(env, 'PATH', f'{p}/bin')
        if os.path.isdir(f'{p}/{site_packages}'):
            prepend(env, 'PYTHONPATH', f'{p}/{site_packages}')
        for pc in ('lib/pkgconfig', 'share/pkgconfig'):
            if os.path.isdir(f'{p}/{pc}'):
                prepend(env, 'PKG_CONFIG_PATH', f'{p}/{pc}')
        # Some CMake configs export bare library names, which Nix's ld
        # wrapper resolves (and adds to the rpath) only via -L flags.
        if os.path.isdir(f'{p}/lib'):
            prepend(env, 'NIX_LDFLAGS', f'-L{p}/lib', sep=' ')
        prepend(env, 'CMAKE_PREFIX_PATH', p)


def source_ament_prefix(env, prefix, bash):
    """Returns env after sourcing the prefix's ament local_setup.sh."""
    # Python would otherwise coerce the locale and add LC_CTYPE to the dump.
    result = subprocess.run(
        [bash, '-c', '. "$1/local_setup.sh" && exec "$2" -c "$3"',
         'bash', prefix, sys.executable, DUMP_ENV],
        env={**env, 'PYTHONCOERCECLOCALE': '0'},
        check=True, capture_output=True, text=True)
    env = json.loads(result.stdout)
    del env['PYTHONCOERCECLOCALE']
    return env


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--env', required=True, help='the buildEnv output')
    parser.add_argument('--site-packages', required=True)
    parser.add_argument('--bash', required=True)
    parser.add_argument('--set', nargs=2, action='append', default=[],
                        metavar=('VAR', 'VALUE'), help='a fixed export')
    parser.add_argument('other_paths', nargs='*',
                        help='outputs of the non-ROS packages to include')
    args = parser.parse_args()

    env = {}
    add_other_packages(env, reversed(args.other_paths), args.site_packages)
    prepend(env, 'NIX_LDFLAGS', f'-L{args.env}/lib', sep=' ')

    if os.path.isfile(f'{args.env}/local_setup.sh'):
        env = source_ament_prefix(env, args.env, args.bash)
    else:
        # Not an ament prefix (ROS 1).
        prepend(env, 'PATH', f'{args.env}/bin')
        prepend(env, 'LD_LIBRARY_PATH', f'{args.env}/lib')
        prepend(env, 'PYTHONPATH', f'{args.env}/{args.site_packages}')
        prepend(env, 'ROS_PACKAGE_PATH', f'{args.env}/share')

    # The rest of what buildEnv's program wrappers set, so that unwrapped
    # programs, such as those built in a colcon workspace on top, see the same.
    prepend(env, 'CMAKE_PREFIX_PATH', args.env)
    if os.path.isdir(f'{args.env}/share/gz'):
        prepend(env, 'GZ_CONFIG_PATH', f'{args.env}/share/gz')
    env.update(dict(args.set))

    print('# Generated by nix-ros-overlay buildEnv; source this file.')
    for var, value in sorted(env.items()):
        if var in SHELL_NOISE:
            continue
        if var == 'NIX_LDFLAGS':
            print(f'export {var}={shlex.quote(value)}"${{{var}:+ ${var}}}"')
        elif '/nix/store/' in value:
            value = ':'.join(p for p in value.split(':') if p)
            print(f'export {var}={shlex.quote(value)}"${{{var}:+:${var}}}"')
        else:
            print(f'export {var}={shlex.quote(value)}')


if __name__ == '__main__':
    main()
